-- ====================================================================
-- SUPABASE CLOUD POSTGRESQL SCHEMA WITH ROW LEVEL SECURITY (RLS)
-- ====================================================================
-- This schema configures PostgreSQL for Supabase Auth and multi-tenant
-- College Attendance Management with strict Row Level Security.
-- Every user can ONLY read, create, update, and delete their own data.
-- ====================================================================

-- 1. Profiles Table (linked to Supabase Auth users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile"
    ON public.profiles FOR SELECT
    USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
    ON public.profiles FOR INSERT
    WITH CHECK (auth.uid() = id);

-- 2. Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
    user_id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    required_attendance NUMERIC DEFAULT 75.0,
    warning_threshold NUMERIC DEFAULT 75.0,
    critical_threshold NUMERIC DEFAULT 65.0,
    theme TEXT DEFAULT 'system',
    college_name TEXT DEFAULT 'College of Engineering & Technology',
    student_name TEXT DEFAULT 'Student',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own settings"
    ON public.settings FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update own settings"
    ON public.settings FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own settings"
    ON public.settings FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- 3. Subjects Table
CREATE TABLE IF NOT EXISTS public.subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    faculty TEXT,
    room TEXT,
    color TEXT DEFAULT '#3B82F6',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own subjects"
    ON public.subjects FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own subjects"
    ON public.subjects FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own subjects"
    ON public.subjects FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own subjects"
    ON public.subjects FOR DELETE
    USING (auth.uid() = user_id);

-- 4. Timetable Table
CREATE TABLE IF NOT EXISTS public.timetable (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    day TEXT NOT NULL,
    period_number INTEGER NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE NOT NULL,
    room TEXT,
    faculty TEXT
);

ALTER TABLE public.timetable ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own timetable"
    ON public.timetable FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own timetable"
    ON public.timetable FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own timetable"
    ON public.timetable FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own timetable"
    ON public.timetable FOR DELETE
    USING (auth.uid() = user_id);

-- 5. Attendance Table
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    date DATE NOT NULL,
    period_id BIGINT REFERENCES public.timetable(id) ON DELETE SET NULL,
    subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Present', 'Absent')),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own attendance"
    ON public.attendance FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own attendance"
    ON public.attendance FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own attendance"
    ON public.attendance FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own attendance"
    ON public.attendance FOR DELETE
    USING (auth.uid() = user_id);

-- 6. Trigger to automatically create profile and settings on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, name, email, avatar_url)
    VALUES (new.id, COALESCE(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)), new.email, new.raw_user_meta_data->>'avatar_url');

    INSERT INTO public.settings (user_id, required_attendance, warning_threshold, critical_threshold, student_name)
    VALUES (new.id, 75.0, 75.0, 65.0, COALESCE(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)));

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 7. Holidays Table (per-user with strict RLS)
CREATE TABLE IF NOT EXISTS public.holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    date DATE NOT NULL,
    name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    UNIQUE(user_id, date)
);

ALTER TABLE public.holidays ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own holidays"
    ON public.holidays FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own holidays"
    ON public.holidays FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own holidays"
    ON public.holidays FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own holidays"
    ON public.holidays FOR DELETE
    USING (auth.uid() = user_id);

